"""create portfolio and portfolio_entitlements tables

Revision ID: 41b4c1466e3d
Revises: 
Create Date: 2024-05-27 14:23:00.825034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41b4c1466e3d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nebulight_portfolio_entitlements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('portfolio_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('permission', sa.Enum('view', 'edit', name='permission_types'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['nebulight_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nebulight_portfolio_entitlements_id'), 'nebulight_portfolio_entitlements', ['id'], unique=False)
    op.drop_table('test')
    op.alter_column('nebulight_portfolios', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('nebulight_portfolios', 'currency',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('nebulight_portfolios', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('nebulight_portfolios', 'owner',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_nebulight_portfolios_id'), 'nebulight_portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_nebulight_portfolios_name'), 'nebulight_portfolios', ['name'], unique=False)
    op.create_index(op.f('ix_nebulight_portfolios_owner'), 'nebulight_portfolios', ['owner'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nebulight_portfolios_owner'), table_name='nebulight_portfolios')
    op.drop_index(op.f('ix_nebulight_portfolios_name'), table_name='nebulight_portfolios')
    op.drop_index(op.f('ix_nebulight_portfolios_id'), table_name='nebulight_portfolios')
    op.alter_column('nebulight_portfolios', 'owner',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('nebulight_portfolios', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('nebulight_portfolios', 'currency',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('nebulight_portfolios', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('test',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='test_pkey')
    )
    op.drop_index(op.f('ix_nebulight_portfolio_entitlements_id'), table_name='nebulight_portfolio_entitlements')
    op.drop_table('nebulight_portfolio_entitlements')
    # ### end Alembic commands ###
