"""add ticker type

Revision ID: 85e07ae3dda7
Revises: b5c6e28ffa31
Create Date: 2024-05-30 23:25:56.280675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85e07ae3dda7'
down_revision: Union[str, None] = 'b5c6e28ffa31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nebulight_tickers', sa.Column('type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nebulight_tickers', 'type')
    # ### end Alembic commands ###
