"""add sector

Revision ID: da944bfc8e62
Revises: 85e07ae3dda7
Create Date: 2024-05-31 18:50:40.323164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da944bfc8e62'
down_revision: Union[str, None] = '85e07ae3dda7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nebulight_sectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_nebulight_sectors_id'), 'nebulight_sectors', ['id'], unique=False)
    op.add_column('nebulight_tickers', sa.Column('sector_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'nebulight_tickers', 'nebulight_sectors', ['sector_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'nebulight_tickers', type_='foreignkey')
    op.drop_column('nebulight_tickers', 'sector_id')
    op.drop_index(op.f('ix_nebulight_sectors_id'), table_name='nebulight_sectors')
    op.drop_table('nebulight_sectors')
    # ### end Alembic commands ###
