org: vitkon
app: nebulight
service: serverless-fastapi
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.9
  region: eu-west-2
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_KEY: ${env:SUPABASE_KEY}

functions:
  scheduledTask:
    handler: src/scheduled_task.scheduled_task_handler
    events:
      - schedule:
          name: hourly-event
          description: Trigger every hour
          rate: cron(0 * * * ? *)
  api:
    handler: src/main.handler
    events:
      - httpApi: "*"

useDotenv: true
plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    slim: true
    strip: false
    noDeploy: []
